### ISSUE TITLE
TimeInABottle Used in Machine java.lang.NullPointerException: null 【When machine low power happen】

### ISSUE THREAD

**Issue by IAmNotGEM** [floppaxd/DeepMobEvolution#34]
[16:30:36] [Server thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.collect.SingletonImmutableList.<init>(SingletonImmutableList.java:38) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.collect.ImmutableList.of(ImmutableList.java:93) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$3.selectNetworks(FMLOutboundHandler.java:115) ~[FMLOutboundHandler$OutboundTarget$3.class:?]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:373) ~[FMLOutboundHandler.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllTracking(SimpleNetworkWrapper.java:276) [SimpleNetworkWrapper.class:?]
	at mustapelto.deepmoblearning.common.network.DMLPacketHandler.sendToClient(DMLPacketHandler.java:32) [DMLPacketHandler.class:?]
	at mustapelto.deepmoblearning.common.tiles.TileEntityMachine.update(TileEntityMachine.java:62) [TileEntityMachine.class:?]
	at lumien.randomthings.entitys.EntityTimeAccelerator.onEntityUpdate(EntityTimeAccelerator.java:98) [EntityTimeAccelerator.class:1.0.1]
	at net.minecraft.entity.Entity.onUpdate(Entity.java:489) [vg.class:?]
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:2387) [amu.class:?]
	at net.minecraft.world.World.updateEntity(World.java:2338) [amu.class:?]
	at net.minecraft.world.World.updateEntities(World.java:2129) [amu.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:744) [oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:897) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:461) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[16:30:36] [Netty Epoll Server IO #2/ERROR] [FML]: There was a critical exception handling a packet on channel deepmoblearning
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.collect.SingletonImmutableList.<init>(SingletonImmutableList.java:38) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.collect.ImmutableList.of(ImmutableList.java:93) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$3.selectNetworks(FMLOutboundHandler.java:115) ~[FMLOutboundHandler$OutboundTarget$3.class:?]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:373) ~[FMLOutboundHandler.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllTracking(SimpleNetworkWrapper.java:276) ~[SimpleNetworkWrapper.class:?]
	at mustapelto.deepmoblearning.common.network.DMLPacketHandler.sendToClient(DMLPacketHandler.java:32) ~[DMLPacketHandler.class:?]
	at mustapelto.deepmoblearning.common.tiles.TileEntityMachine.update(TileEntityMachine.java:62) ~[TileEntityMachine.class:?]
	at lumien.randomthings.entitys.EntityTimeAccelerator.onEntityUpdate(EntityTimeAccelerator.java:98) ~[EntityTimeAccelerator.class:1.0.1]
	at net.minecraft.entity.Entity.onUpdate(Entity.java:489) ~[vg.class:?]
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:2387) ~[amu.class:?]
	at net.minecraft.world.World.updateEntity(World.java:2338) ~[amu.class:?]
	at net.minecraft.world.World.updateEntities(World.java:2129) ~[amu.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:744) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:897) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:461) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:778) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

**Comment by IAmNotGEM** [comment]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[16:30:36] [Server thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.collect.SingletonImmutableList.<init>(SingletonImmutableList.java:38) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.collect.ImmutableList.of(ImmutableList.java:93) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$3.selectNetworks(FMLOutboundHandler.java:115) ~[FMLOutboundHandler$OutboundTarget$3.class:?]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:373) ~[FMLOutboundHandler.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllTracking(SimpleNetworkWrapper.java:276) [SimpleNetworkWrapper.class:?]
	at mustapelto.deepmoblearning.common.network.DMLPacketHandler.sendToClient(DMLPacketHandler.java:32) [DMLPacketHandler.class:?]
	at mustapelto.deepmoblearning.common.tiles.TileEntityMachine.update(TileEntityMachine.java:62) [TileEntityMachine.class:?]
	at lumien.randomthings.entitys.EntityTimeAccelerator.onEntityUpdate(EntityTimeAccelerator.java:98) [EntityTimeAccelerator.class:1.0.1]
	at net.minecraft.entity.Entity.onUpdate(Entity.java:489) [vg.class:?]
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:2387) [amu.class:?]
	at net.minecraft.world.World.updateEntity(World.java:2338) [amu.class:?]
	at net.minecraft.world.World.updateEntities(World.java:2129) [amu.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:744) [oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:897) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:461) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[16:30:36] [Netty Epoll Server IO #2/ERROR] [FML]: There was a critical exception handling a packet on channel deepmoblearning
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.collect.SingletonImmutableList.<init>(SingletonImmutableList.java:38) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.collect.ImmutableList.of(ImmutableList.java:93) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$3.selectNetworks(FMLOutboundHandler.java:115) ~[FMLOutboundHandler$OutboundTarget$3.class:?]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:373) ~[FMLOutboundHandler.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllTracking(SimpleNetworkWrapper.java:276) ~[SimpleNetworkWrapper.class:?]
	at mustapelto.deepmoblearning.common.network.DMLPacketHandler.sendToClient(DMLPacketHandler.java:32) ~[DMLPacketHandler.class:?]
	at mustapelto.deepmoblearning.common.tiles.TileEntityMachine.update(TileEntityMachine.java:62) ~[TileEntityMachine.class:?]
	at lumien.randomthings.entitys.EntityTimeAccelerator.onEntityUpdate(EntityTimeAccelerator.java:98) ~[EntityTimeAccelerator.class:1.0.1]
	at net.minecraft.entity.Entity.onUpdate(Entity.java:489) ~[vg.class:?]
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:2387) ~[amu.class:?]
	at net.minecraft.world.World.updateEntity(World.java:2338) ~[amu.class:?]
	at net.minecraft.world.World.updateEntities(World.java:2129) ~[amu.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:744) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:897) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:461) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:778) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
